"""Print harvested monthly revenue candidates for human review. Research only."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


def write_review_sheet(input_path: str, output_path: str) -> None:
    """List the candidates the importer held back, with the sentence behind each.

    Machine extraction is deliberately strict, so usable figures sit in the
    held-back pile. A person can approve or reject each row from the sentence
    alone, which is faster than reading the articles again.
    """
    payload = json.loads((ROOT / input_path).read_text(encoding='utf-8'))
    held_back = [row for row in payload['rows'] if not row['keep']]
    by_flag: dict[str, list[dict]] = {}
    for row in held_back:
        for flag in row['flags']:
            by_flag.setdefault(flag, []).append(row)
    lines = [
        '# Held-back monthly figures, for human review',
        '',
        'Generated by `scripts/revenue-research/review_harvest.py --markdown`. These',
        'rows were extracted but not imported, each with the rule that stopped it and',
        'the sentence it came from. Approving one means adding it to a manual anchor',
        'file by hand, with the same period, store and fee scope as its article.',
        '',
        f"Source: `{input_path}` - {len(payload['rows'])} candidates, "
        f"{len(payload['rows']) - len(held_back)} imported, {len(held_back)} held back.",
        '',
    ]
    for flag, rows in sorted(by_flag.items(), key=lambda item: -len(item[1])):
        lines += [f'## {flag} ({len(rows)})', '',
                  '| Period | Game | Amount ($M) | Sentence |', '| --- | --- | --- | --- |']
        for row in sorted(rows, key=lambda item: (item['period_start'], item['game'])):
            sentence = row['sentence'].replace('|', '/')
            lines.append(f"| {row['period_start']} | {row['game']} | {row['amount_usd_m']} "
                         f"| {sentence[:160]} |")
        lines.append('')
    (ROOT / output_path).write_text('\n'.join(lines) + '\n', encoding='utf-8')
    return {'output': output_path, 'held_back': len(held_back),
            'flags': {flag: len(rows) for flag, rows in sorted(by_flag.items())}}


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument('--input', default='reports/rank-models/monthly-chart-harvest-2026-09-11.json')
    parser.add_argument('--all', action='store_true')
    parser.add_argument('--limit', type=int, default=200)
    parser.add_argument('--markdown', default='',
                        help='write a human review sheet of the held-back candidates')
    arguments = parser.parse_args()
    if arguments.markdown:
        print(json.dumps(write_review_sheet(arguments.input, arguments.markdown)))
        return

    payload = json.loads((ROOT / arguments.input).read_text(encoding='utf-8'))
    rows = payload['rows']
    kept = [row for row in rows if row['keep']]
    counts: dict[str, int] = {}
    for row in rows:
        for flag in row['flags'] or ['-']:
            counts[flag] = counts.get(flag, 0) + 1
    print('flags:', ', '.join(f'{flag}={count}' for flag, count in sorted(counts.items(), key=lambda item: -item[1])))
    print(f"rows {len(rows)} kept {len(kept)} articles {len(payload['articles'])}")
    for article in payload['articles']:
        print(f"  article {article['url'].rstrip('/').split('/')[-1]} status {article['status']} rows {article['rows']}")
    for row in (rows if arguments.all else kept)[:arguments.limit]:
        flags = ','.join(row['flags']) or '-'
        print(f"{row['period_start']} | {row['game'][:28]:28} | {row['amount_usd_m']:>7} | "
              f"{row['attribution'][:10]:10} | {row['month_basis'][:14]:14} | {flags[:28]:28} | {row['sentence'][:100]}")


if __name__ == '__main__':
    main()
